apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-deployment
  namespace: app3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cat
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
      - name: cat
        image: neytor/catcontainer
        ports:
        - containerPort: 80
